# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
#    metrics_path: '/actuator/prometheus'

    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: rabbitmq
    scrape_interval: 5s
    scrape_timeout: 4s
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['localhost:15672']

  - job_name: 'cemis-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9091']

  - job_name: 'nginx-server-local'
    metrics_path: '/metrics'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9113']

  - job_name: 'authorization-server-local'
    metrics_path: '/auth/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'nginx-server-test'
    metrics_path: '/metrics'
    scrape_interval: 1s
    static_configs:
      - targets: ['192.168.0.171:9113']

  - job_name: 'authorization-server-test-1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.171:9999']

  - job_name: 'authorization-server-test-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.171:9998']

  - job_name: 'node-server-test'
    static_configs:
      - targets: ['192.168.0.171:9100']

  - job_name: 'data-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['localhost:9104']
